  id_Cut     = 1;
  id_Copy    = 2;
  id_Paste   = 3;
  id_UNDO    = 4;
  id_redo    = 5;
  id_Del     = 6;
  id_New     = 7;
  id_ODos    = 8;
  id_Save    = 9;
  id_View    = 10;
  id_Char    = 11;
  id_Help    = 12;
  id_Find    = 13;
  id_Replace = 14;
  id_Print   = 15;
  id_ANSI    = 16;
  id_OEM     = 17;
  id_KOI8R   = 18;

  id_justify = 19;
  id_center  = 20;
  id_left    = 21;
  id_right   = 22;
  id_Header  = 23;
  id_Setup   = 24;
  id_WordWrap= 25;
  id_SaveAs  = 26;


  id_other   = 27;
  id_Sea     = 28;
  id_ToWin   = 29;
  id_ToDos   = 30;
  id_tokoi8  = 31;
  id_Fido    = 32;
  id_Translit= 33;
  id_RTF     = 34;
  id_Quoted  = 35;

  id_Break   = 36;
  id_Options = 37;

  id_insert  = 38;
  id_Date    = 39;
  id_UserW   = 40;
  id_UserD   = 41;
  id_UserK   = 42;
  id_Hack    = 43;


  id_Exit    = 44;
  id_ToolBar = 45;
  id_BColor  = 46;
  id_FColor  = 47;
  id_Select  = 48;
  id_SizeP   = 49;
  id_SizeM   = 50;
  id_About   = 51;

  id_HTMLColor=52;
  id_HTML    = 53;

  id_sdown    = 200;
  id_sup      = 201;
  id_sleft    = 202;
  id_sright   = 203;

  id_ddown   = 204;
  id_dup     = 205;
  id_dleft   = 206;
  id_dright  = 207;

  bmps=53;
  bmpp=23;
























